stages:
    - build
    - publish

build_python3:
    stage: build
    allow_failure: false
    only:
        - tags
    image: python:3.6
    script:
        - pip install --upgrade setuptools wheel
        - python setup.py sdist bdist_wheel
    artifacts:
        paths:
            - dist/

publish_package:
    stage: publish
    allow_failure: false
    only:
        - tags
    image: python:3.6
    script:
        - pip install --upgrade setuptools wheel twine
        - ls -l dist/*
        - twine upload dist/*
